DELIMITER //
CREATE DATABASE IF NOT EXISTS example//
USE example//

DROP FUNCTION IF EXISTS FIBONACCI;
CREATE FUNCTION FIBONACCI (num INT)
RETURNS INT NOT DETERMINISTIC
BEGIN
	DECLARE i INT DEFAULT 1;
	DECLARE c INT DEFAULT 0;
	DECLARE a INT DEFAULT 0;
	DECLARE b INT DEFAULT 1;
	
	IF(num=1) THEN
		RETURN b;
	END IF;
	
	WHILE i<num DO
		SET c = a + b;
		SET a = b;
		SET b = c;
		SET i = i + 1;
	END WHILE;

  RETURN c;
END//

SELECT FIBONACCI(0) AS '0'
, FIBONACCI(1) AS '1'
, FIBONACCI(2) AS '2'
, FIBONACCI(3) AS '3'
, FIBONACCI(4) AS '4'
, FIBONACCI(5) AS '5'
, FIBONACCI(6) AS '6'
, FIBONACCI(7) AS '7'
, FIBONACCI(8) AS '8'
, FIBONACCI(9) AS '9'
, FIBONACCI(10) AS '10'//